name: 'DeployNow Configuration Templating'
description: 'Fill templates of configuration files before deployment based on the golang template engine'
inputs:
  template-directory:
    description: 'The directory to search for template files'
    required: false
    default: '.deploy-now'
  template-extension:
    description: 'The file extension which identifies template files'
    required: false
    default: '.template'
  output-directory:
    description: 'The directory where the processed templates will be written to'
    required: false
    default: './'
  data:
    description: 'Data to use for rendering templates as yaml or json objects'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '--template-dir'
    - ${{ inputs.template-directory }}
    - '--template-extension'
    - ${{ inputs.template-extension }}
    - '--output-dir'
    - ${{ inputs.output-directory }}
    - '--data'
    - ${{ inputs.data }}
    - '--copy-permissions'